namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -44)]
		public static void A794e9d4b_1629_4d54_805f_06654469ea9b() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -43)]
		public static void Ad995a6ef_3d03_464d_80b3_6a82a597843b() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -42)]
		public static void Aecf90535_785b_43f2_88cb_fd90c228e4f1() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -41)]
		public static void A9350485b_3183_4c66_8f50_88872bf7fc51() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -39)]
		public static void A6854c5a9_534f_48e0_92ab_05dcc8edd48d() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -38)]
		public static void A15746162_724c_4460_8318_7588f4f991f6() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -37)]
		public static void A443aa7c0_b06e_49d2_ac87_030333144ce7() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -36)]
		public static void Ab3fd621a_f187_4287_b87a_4de41ff50e50() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -36)]
		public static void A405fe6ad_dc89_4777_ae86_45b0651cec3f() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -35)]
		public static void Acfa730f6_be41_45a0_a07e_88901fd0b09d() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -34)]
		public static void A3cf93e58_e8fc_4779_a401_5336ef8f7e27() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -33)]
		public static void Aceeb669a_5e0d_4965_b7ec_6264440be764() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -32)]
		public static void A8440bdea_2f59_491d_aa32_8be3792fc77d() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -31)]
		public static void A7d7f55f9_4ccd_44d6_b648_42d92bdee864() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -30)]
		public static void A0394879f_cd57_4e38_8c0a_3343e9dd0c84() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -29)]
		public static void A0ce4d3cf_9412_4297_aa50_c30279ae1014() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -28)]
		public static void A024b2aaf_5008_498b_b0c1_adedfa03aa50() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -27)]
		public static void A50687607_7be0_4e37_88ae_0e4246f5523c() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateLightmapUVs()); }

		[MenuItem("Pixyz/Toolbox/Misc/Save as .pxz", priority = 22)]
		[MenuItem("GameObject/Pixyz/Misc/Save as .pxz", priority = -3)]
		public static void A1e3d88eb_83de_479c_b38c_116f43d04a08() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.SaveAction()); }

	}
}